### ISSUE TITLE
shore-config - shore config used to determine renderer/executor

### ISSUE THREAD

**Issue by eyalmor-ent** [Autodesk/shore#26]
# Description

Original Author: @dkirillov
The `Renderer` and Executor/`Backend` which are part of `Dependencies` should now be determined by the `renderer.type` and `executor.type` found in the shore config.

For this, the shore config will need to be loaded. `PersistentPreRunE` for the root command runs _before_ any of the other commands run, so most likely this would be the places where the shore config is loaded (`LoadShoreConfig` used from #174).

Example shore config:
```yml
renderer:
  type: jsonnet

executor:
  type: spinnaker
  config:
    ...

profiles:
  default:
    ...
```

This will set the `Renderer` to `jsonnet` and the Executor/`Backend` to `spinnaker` in the `Dependencies`.

Currently, there are only `jsonnet` and `spinnaker` types.
