### ISSUE TITLE
shore-config - exec command using shore config with the correct profile

### ISSUE THREAD

**Issue by eyalmor-ent** [Autodesk/shore#29]
## Summary

Original Author: @dkirillov
`shore exec` command should now use the exec config specified in the shore config.

Specifically, in the shore config it is stored under the following path - `profiles.[profile-name].exec`. Example shore config:

```yml
renderer:
  ...

executor:
  ...

profiles:
  default:
    application: \"myAppName\"
    pipeline: \"awesome-pipeline\"
    render:  ... # Path or Object
    exec: ... # Path or Object
    e2e: ... # Path or Object

```

What is present in the profile could either be the full exec config object (in-line config), or a path to the `exec.yml` file (external config). Either or is allowed and should be used.
