### ISSUE TITLE
shore-config - test-remote command using shore config with the correct profile

### ISSUE THREAD

**Issue by eyalmor-ent** [Autodesk/shore#31]
## Summary

Original Author: @dkirillov
`shore test-remote` command should now use the E2E config specified in the shore config.

Specifically, in the shore config it is stored under the following path - `profiles.[profile-name].e2e`. Example shore config:

```yml
renderer:
  ...

executor:
  ...

profiles:
  default:
    application: \"myAppName\"
    pipeline: \"awesome-pipeline\"
    render:  ... # Path or Object
    exec: ... # Path or Object
    e2e: ... # Path or Object

```

What is present in the profile could either be the full E2E config object (in-line config), or a path to the `E2E.yml` file (external config). Either or is allowed and should be used.
